/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package booksql.GUIComponents.Views;

import booksql.DatabaseAccess;
import booksql.StatsDAO;

/**
 *
 * @author zander
 */
public class StatsView extends javax.swing.JPanel {

    private StatsDAO statsDAO;

    /**
     * Creates new form StatsView
     */
    public StatsView() {
        initComponents();
        this.statsDAO = DatabaseAccess.getStatsDAO();
        loadStats();
    }

    private void loadStats() {
        int mPopBookId;
        String mPopBookTitle;
        int mPopBookTimes;

        int lPopBookId;
        String lPopBookTitle;
        int lPopBookTimes;

        String mPopGenre;

        String lPopGenre;

        int userId;
        String userName;
        int userNumBooks;

        try {
            Object[] mPop = this.statsDAO.getMPopBook();
            Object[] lPop = this.statsDAO.getLPopBook();
            String[] genres = this.statsDAO.getGenres();
            Object[] user = this.statsDAO.getMUser();

            mPopBookId = (int) mPop[0];
            mPopBookTitle = (String) mPop[1];
            mPopBookTimes = (int) mPop[2];

            lPopBookId = (int) lPop[0];
            lPopBookTitle = (String) lPop[1];
            lPopBookTimes = (int) lPop[2];

            mPopGenre = genres[0];
            lPopGenre = genres[1];

            userId = (int) user[0];
            userName = (String) user[1];
            userNumBooks = (int) user[2];

        } catch (Exception e) {
            e.printStackTrace();
            return;
        }

        // set labels here
        mCheckedOutId.setText(setLabel(mCheckedOutId.getText(), mPopBookId));
        mCheckedOutTitle.setText(setLabel(mCheckedOutTitle.getText(), mPopBookTitle));
        mCheckedOutTimes.setText(setLabel(mCheckedOutTimes.getText(), mPopBookTimes));
        
        lCheckedOutId.setText(setLabel(lCheckedOutId.getText(), lPopBookId));
        lCheckedOutTitle.setText(setLabel(lCheckedOutTitle.getText(), lPopBookTitle));
        lCheckedOutTimes.setText(setLabel(lCheckedOutTimes.getText(), lPopBookTimes));
        
        this.mPopGenre.setText(setLabel(this.mPopGenre.getText(), mPopGenre));
        this.lPopGenre.setText(setLabel(this.lPopGenre.getText(), lPopGenre));
        
        mCOUserId.setText(setLabel(mCOUserId.getText(), userId));
        mCOUserName.setText(setLabel(mCOUserName.getText(), userName));
        mCOUserNumBooks.setText(setLabel(mCOUserNumBooks.getText(), userNumBooks));
    }

    //Sub $ in labels with value
    private String setLabel(String text, Object item) {
        return text.replace("$", item.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mostCheckedOutLabel = new javax.swing.JLabel();
        leastCheckedOutLabel = new javax.swing.JLabel();
        mostUserLabel = new javax.swing.JLabel();
        mCheckedOutId = new javax.swing.JLabel();
        mCheckedOutTitle = new javax.swing.JLabel();
        mostPopGenreLabel = new javax.swing.JLabel();
        leastPopGenreLabel = new javax.swing.JLabel();
        lCheckedOutId = new javax.swing.JLabel();
        lCheckedOutTitle = new javax.swing.JLabel();
        mPopGenre = new javax.swing.JLabel();
        lPopGenre = new javax.swing.JLabel();
        mCOUserId = new javax.swing.JLabel();
        mCOUserName = new javax.swing.JLabel();
        mCheckedOutTimes = new javax.swing.JLabel();
        lCheckedOutTimes = new javax.swing.JLabel();
        mCOUserNumBooks = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        errorLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(52, 81, 128));
        setPreferredSize(new java.awt.Dimension(3, 160));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Stats View");

        mostCheckedOutLabel.setForeground(new java.awt.Color(255, 255, 255));
        mostCheckedOutLabel.setText("Most Checked out Book:");

        leastCheckedOutLabel.setForeground(new java.awt.Color(255, 255, 255));
        leastCheckedOutLabel.setText("Least Checked out Book:");

        mostUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        mostUserLabel.setText("User with the most checked out Books:");

        mCheckedOutId.setForeground(new java.awt.Color(255, 255, 255));
        mCheckedOutId.setText("Id: $");

        mCheckedOutTitle.setForeground(new java.awt.Color(255, 255, 255));
        mCheckedOutTitle.setText("Title: $");

        mostPopGenreLabel.setForeground(new java.awt.Color(255, 255, 255));
        mostPopGenreLabel.setText("Most Popular Genre:");

        leastPopGenreLabel.setForeground(new java.awt.Color(255, 255, 255));
        leastPopGenreLabel.setText("Least Popular Genre:");

        lCheckedOutId.setForeground(new java.awt.Color(255, 255, 255));
        lCheckedOutId.setText("Id: $");

        lCheckedOutTitle.setForeground(new java.awt.Color(255, 255, 255));
        lCheckedOutTitle.setText("Title: $");

        mPopGenre.setForeground(new java.awt.Color(255, 255, 255));
        mPopGenre.setText("Genre: $");

        lPopGenre.setForeground(new java.awt.Color(255, 255, 255));
        lPopGenre.setText("Genre: $");

        mCOUserId.setForeground(new java.awt.Color(255, 255, 255));
        mCOUserId.setText("Id: $");

        mCOUserName.setForeground(new java.awt.Color(255, 255, 255));
        mCOUserName.setText("Name: $");

        mCheckedOutTimes.setForeground(new java.awt.Color(255, 255, 255));
        mCheckedOutTimes.setText("Checked Out : $ times");

        lCheckedOutTimes.setForeground(new java.awt.Color(255, 255, 255));
        lCheckedOutTimes.setText("Checked Out : $ times");

        mCOUserNumBooks.setForeground(new java.awt.Color(255, 255, 255));
        mCOUserNumBooks.setText("Has $ Books Checked Out");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setMinimumSize(null);
        jSeparator1.setPreferredSize(new java.awt.Dimension(3, 160));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setMinimumSize(null);
        jSeparator2.setPreferredSize(new java.awt.Dimension(3, 160));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setMinimumSize(null);
        jSeparator3.setPreferredSize(new java.awt.Dimension(3, 160));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setMinimumSize(null);
        jSeparator4.setPreferredSize(new java.awt.Dimension(3, 160));

        errorLabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mCheckedOutTimes)
                            .addComponent(mostCheckedOutLabel)
                            .addComponent(mCheckedOutId)
                            .addComponent(mCheckedOutTitle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leastCheckedOutLabel)
                    .addComponent(lCheckedOutId)
                    .addComponent(lCheckedOutTitle)
                    .addComponent(lCheckedOutTimes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mostPopGenreLabel)
                    .addComponent(mPopGenre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leastPopGenreLabel)
                    .addComponent(lPopGenre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mCOUserNumBooks)
                    .addComponent(mCOUserId)
                    .addComponent(mostUserLabel)
                    .addComponent(mCOUserName))
                .addGap(287, 287, 287))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mostCheckedOutLabel)
                                    .addComponent(leastCheckedOutLabel)
                                    .addComponent(mostUserLabel)
                                    .addComponent(mostPopGenreLabel)
                                    .addComponent(leastPopGenreLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mCheckedOutId)
                                    .addComponent(lCheckedOutId, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mPopGenre)
                                    .addComponent(lPopGenre)
                                    .addComponent(mCOUserId))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mCOUserName)
                                    .addComponent(lCheckedOutTitle)
                                    .addComponent(mCheckedOutTitle))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mCheckedOutTimes)
                                    .addComponent(lCheckedOutTimes)
                                    .addComponent(mCOUserNumBooks))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lCheckedOutId;
    private javax.swing.JLabel lCheckedOutTimes;
    private javax.swing.JLabel lCheckedOutTitle;
    private javax.swing.JLabel lPopGenre;
    private javax.swing.JLabel leastCheckedOutLabel;
    private javax.swing.JLabel leastPopGenreLabel;
    private javax.swing.JLabel mCOUserId;
    private javax.swing.JLabel mCOUserName;
    private javax.swing.JLabel mCOUserNumBooks;
    private javax.swing.JLabel mCheckedOutId;
    private javax.swing.JLabel mCheckedOutTimes;
    private javax.swing.JLabel mCheckedOutTitle;
    private javax.swing.JLabel mPopGenre;
    private javax.swing.JLabel mostCheckedOutLabel;
    private javax.swing.JLabel mostPopGenreLabel;
    private javax.swing.JLabel mostUserLabel;
    // End of variables declaration//GEN-END:variables
}
