/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package booksql.forms;

import booksql.GUIComponents.Views.PublisherSearchView;
import booksql.PublisherDAO;
import booksql.DataModels.Publisher;

import java.awt.event.*;
import java.awt.*;

import javax.swing.*;
import java.time.format.DateTimeParseException;
import java.time.*;
import java.util.Date;
import java.time.ZoneId;
import java.util.HashSet;
import java.util.Set;


/**
 *
 * @author emarz
 */
public class publisherAdd extends JFrame {
    private PublisherSearchView parentView;
    
public publisherAdd(PublisherSearchView parentView) {
        super("Add Publisher"); // Title of the JFrame
        this.parentView = parentView;
        initComponents(); // Initialize components
        setupSaveButton(); // Setup the Save button manually

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        pack();
        setAlwaysOnTop(rootPaneCheckingEnabled);
    
        setVisible(true); // Show JFrame
    }
    
    public publisherAdd() {
        this(null); // Calls the main constructor with null for parent and parentView
    }

    // Method to setup the Save button and its action
    private void setupSaveButton() {
        // The button is already in initComponents() so no need to add it manually
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                savePublisher(); // Action to save the publisher
            }
        });
    }

    // Method to handle saving the publisher to the database
    private void savePublisher() {
        String name = jTextField4.getText().trim();
        String email = jTextField5.getText().trim();
        String dateText = jTextField6.getText().trim();
        LocalDate dateFounded;

        try {
            dateFounded = LocalDate.parse(dateText);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Invalid Date Format (yyyy-mm-dd).");
            return;
        }

        if (name.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled out.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            PublisherDAO publisherDAO = booksql.DatabaseAccess.getPublisherDAO();
            java.sql.Date sqlDate = java.sql.Date.valueOf(dateFounded);
            Publisher newPublisher = new Publisher(0, name, sqlDate, email);

            publisherDAO.insertPublisher(newPublisher);
            JOptionPane.showMessageDialog(this, "Publisher added successfully!");

            if (parentView != null) {
                parentView.loadPublishers(); // Reload publisher data in the parent view
            }

            dispose(); // Close JFrame after saving
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error saving publisher: " + e.getMessage());
        }    
    
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField4.setName("nameInput"); // NOI18N

        jTextField5.setName("emailInput"); // NOI18N

        jTextField6.setText("(yyyy-mm-dd)");
        jTextField6.setName("dateFoundedInput"); // NOI18N

        jLabel4.setText("Name:");
        jLabel4.setName("name"); // NOI18N

        jLabel5.setText("Email:");
        jLabel5.setName("email"); // NOI18N

        jLabel6.setText("Date Founded:");
        jLabel6.setName("dateFounded"); // NOI18N

        jButton1.setText("Add Publisher");
        jButton1.setName("addButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField5)
                        .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addComponent(jTextField4)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
