/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package booksql.GUIComponents;

import booksql.assets.ImageLoader;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JPanel;

public class Navbar extends javax.swing.JPanel {
    
    ArrayList<NavbarListener> listeners;
    /**
     * Creates new form NavBar
     */
    public Navbar() {
        initComponents();
        initLogo();
        
        
        this.listeners = new ArrayList();
        initButtons();
    }
    
    private void initLogo(){
//      logoPanel logoP = new logoPanel();
        try{ 
            this.logoHolder.setSize(200, 200);
            this.logoHolder.setText("");
            this.logoHolder.setIcon(ImageLoader.loadIcon(ImageLoader.LOGOURL, this.logoHolder.getWidth(), this.logoHolder.getHeight()));
        } catch(IOException io){
            io.printStackTrace();
        }
    }
        
    
    private void initButtons(){
        this.homeBtn.addActionListener(new NavbarBtnClickListener(View.HOME));
        this.checkInBtn.addActionListener(new NavbarBtnClickListener(View.CHECKIN));
        this.checkOutBtn.addActionListener(new NavbarBtnClickListener(View.CHECKOUT));
        this.userLUpBtn.addActionListener(new NavbarBtnClickListener(View.USERLOOKUP));
        this.bookSearchBtn.addActionListener(new NavbarBtnClickListener(View.BOOKSEARCH));
        this.authorSearchBtn.addActionListener(new NavbarBtnClickListener(View.AUTHORSEARCH));
        this.publisherSearchBtn.addActionListener(new NavbarBtnClickListener(View.PUBLISHERSEARCH));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        navBarPanel = new javax.swing.JPanel();
        logoHolder = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        checkOutBtn = new javax.swing.JButton();
        checkInBtn = new javax.swing.JButton();
        userLUpBtn = new javax.swing.JButton();
        bookSearchBtn = new javax.swing.JButton();
        authorSearchBtn = new javax.swing.JButton();
        publisherSearchBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(200, 600));
        setRequestFocusEnabled(false);

        navBarPanel.setBackground(new java.awt.Color(255, 153, 0));
        navBarPanel.setForeground(new java.awt.Color(255, 255, 255));
        navBarPanel.setPreferredSize(new java.awt.Dimension(200, 2000));
        navBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoHolder.setText("logo");
        logoHolder.setPreferredSize(new java.awt.Dimension(200, 200));
        navBarPanel.add(logoHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 200));

        homeBtn.setBackground(new java.awt.Color(204, 204, 204));
        homeBtn.setForeground(new java.awt.Color(51, 51, 51));
        homeBtn.setText("Home");
        homeBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        homeBtn.setPreferredSize(new java.awt.Dimension(146, 40));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        navBarPanel.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 188, -1));

        checkOutBtn.setBackground(new java.awt.Color(204, 204, 204));
        checkOutBtn.setForeground(new java.awt.Color(51, 51, 51));
        checkOutBtn.setText("Check Out Book");
        checkOutBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkOutBtn.setPreferredSize(new java.awt.Dimension(146, 40));
        checkOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutBtnActionPerformed(evt);
            }
        });
        navBarPanel.add(checkOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 188, -1));

        checkInBtn.setBackground(new java.awt.Color(204, 204, 204));
        checkInBtn.setForeground(new java.awt.Color(51, 51, 51));
        checkInBtn.setText("Check In Book");
        checkInBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkInBtn.setPreferredSize(new java.awt.Dimension(146, 40));
        navBarPanel.add(checkInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 188, -1));

        userLUpBtn.setBackground(new java.awt.Color(204, 204, 204));
        userLUpBtn.setForeground(new java.awt.Color(51, 51, 51));
        userLUpBtn.setText("User Lookup");
        userLUpBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userLUpBtn.setPreferredSize(new java.awt.Dimension(146, 40));
        navBarPanel.add(userLUpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 188, -1));

        bookSearchBtn.setBackground(new java.awt.Color(204, 204, 204));
        bookSearchBtn.setForeground(new java.awt.Color(51, 51, 51));
        bookSearchBtn.setText("Book Search");
        bookSearchBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bookSearchBtn.setPreferredSize(new java.awt.Dimension(146, 40));
        navBarPanel.add(bookSearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 188, -1));

        authorSearchBtn.setBackground(new java.awt.Color(204, 204, 204));
        authorSearchBtn.setForeground(new java.awt.Color(51, 51, 51));
        authorSearchBtn.setText("Author Search");
        authorSearchBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        authorSearchBtn.setPreferredSize(new java.awt.Dimension(146, 40));
        authorSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorSearchBtnActionPerformed(evt);
            }
        });
        navBarPanel.add(authorSearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 188, -1));

        publisherSearchBtn.setBackground(new java.awt.Color(204, 204, 204));
        publisherSearchBtn.setForeground(new java.awt.Color(51, 51, 51));
        publisherSearchBtn.setText("Publisher Search");
        publisherSearchBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        publisherSearchBtn.setPreferredSize(new java.awt.Dimension(146, 40));
        navBarPanel.add(publisherSearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 188, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(navBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(navBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkOutBtnActionPerformed

    private void authorSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorSearchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorSearchBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton authorSearchBtn;
    private javax.swing.JButton bookSearchBtn;
    private javax.swing.JButton checkInBtn;
    private javax.swing.JButton checkOutBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logoHolder;
    private javax.swing.JPanel navBarPanel;
    private javax.swing.JButton publisherSearchBtn;
    private javax.swing.JButton userLUpBtn;
    // End of variables declaration//GEN-END:variables

    public enum View{
        HOME,
        CHECKIN,
        CHECKOUT,
        USERLOOKUP,
        BOOKSEARCH,
        AUTHORSEARCH,
        PUBLISHERSEARCH,
        DBERROR,
    }
    
    public void addListener(NavbarListener listener){
        this.listeners.add(listener);
    }
    
    public void removeListener(NavbarListener listener){
        this.listeners.remove(listener);
    }
    
    private void notifyListeners(View v){
        for(NavbarListener listener : this.listeners){
            listener.onNavBtnClicked(v);
        }
    }

    private class NavbarBtnClickListener implements ActionListener {
        private View v;
        
        public NavbarBtnClickListener(View view){
            this.v = view;
        }
        

        @Override
        public void actionPerformed(ActionEvent e) {
            notifyListeners(this.v);
        }
        
    }
    
    private class logoPanel extends JPanel{
        BufferedImage logo;
        @Override
        protected void paintComponent(Graphics g){
            super.paint(g);
            g.drawImage(logo, 0, 0, null);
        }
    }

}
