/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package booksql.GUIComponents;

import booksql.GUIComponents.Navbar.View;
import booksql.GUIComponents.Views.*;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JPanel;

/**
 *
 * @author zander
 */
public class Window extends javax.swing.JFrame implements NavbarListener{

    private Navbar nav;
    private JPanel currentView;
    HashMap<View, JPanel> views;
    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        this.views = new HashMap<>(7);
        initViews();
        
        this.nav = new Navbar();
        this.add(this.nav, BorderLayout.WEST);
        this.nav.addListener(this);
        
        changeVeiw(View.HOME);
    }
    
    private void initViews(){
        this.views.put(View.HOME, new HomeView());
        this.views.put(View.CHECKIN, new CheckInView());
        this.views.put(View.CHECKOUT, new CheckOutView());
        this.views.put(View.USERLOOKUP, new UserLookUpView());
        this.views.put(View.BOOKSEARCH, new BookSearchView());
        this.views.put(View.AUTHORSEARCH, new AuthorSearchView());
        this.views.put(View.PUBLISHERSEARCH, new PublisherSearchView());
    }
    
    @Override
    public void onNavBtnClicked(View v) {
        changeVeiw(v);
    }
    
    
    private void changeVeiw(View v){
        JPanel newView = this.views.get(v);
        if(newView != null){
            if(this.currentView != null){
                this.remove(currentView);
                System.out.println("Removed View :" + this.currentView.toString());
            }
            this.add(newView, BorderLayout.CENTER);
            this.currentView = newView;
            System.out.println("Changed view to : " + this.currentView.toString());
        }
        else{
            System.out.println("Unable to find view: " + v.name());
        }
        
        revalidate();
        repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Booksql");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
